# Generated by Django 6.0.3 on 2026-03-24 11:57

import video_app.validate_video
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('original_file', models.FileField(upload_to='originals/', validators=[video_app.validate_video.validate_video_file])),
                ('hls_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
